### PR TITLE
Translation of the radio strings in French

### PR DESCRIPTION
**Pull request by arceusdev**
PR containing the new radio strings translated in French

### CODE REVIEW

**Comment by fb-sean** [comment]
@0x2b67 is this one done?

**Comment by fb-sean** [comment]
Added something I forgot

**Comment by arceusdev** [comment]
Yeah @fb-sean, it's done, I edited the string you added
Is there one I've missed?

**Comment by fb-sean** [comment]
> Yeah @fb-sean, it's done, I edited the string you added Is there one I've missed?

I mean I hope so xD

**Comment by fb-sean** [comment]
Could you try to resolve the conflict?

**Comment by arceusdev** [comment]
The conflict should be resolved now 👍🏻

**Pull request merged**
